CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(30) NOT NULL,
    "DisplayOrder" integer NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "ISBN" text NOT NULL,
    "Author" text NOT NULL,
    "ListPrice" double precision NOT NULL,
    "Price" double precision NOT NULL,
    "Price50" double precision NOT NULL,
    "Price100" double precision NOT NULL,
    "CategoryId" integer,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id")
);

INSERT INTO "Categories" ("Id", "DisplayOrder", "Name")
VALUES (1, 1, 'Action');
INSERT INTO "Categories" ("Id", "DisplayOrder", "Name")
VALUES (2, 2, 'SciFi');
INSERT INTO "Categories" ("Id", "DisplayOrder", "Name")
VALUES (3, 3, 'History');

INSERT INTO "Products" ("Id", "Author", "CategoryId", "Description", "ISBN", "ListPrice", "Price", "Price100", "Price50", "Title")
VALUES (1, 'Billy Spark', NULL, 'Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.

Nunc malesuada viverra ipsum sit amet tincidunt. ', 'SWD9999001', 99.0, 90.0, 80.0, 85.0, 'Fortune of Time');
INSERT INTO "Products" ("Id", "Author", "CategoryId", "Description", "ISBN", "ListPrice", "Price", "Price100", "Price50", "Title")
VALUES (2, 'Nancy Hoover', NULL, 'Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.

Nunc malesuada viverra ipsum sit amet tincidunt. ', 'CAW777777701', 40.0, 30.0, 20.0, 25.0, 'Dark Skies');
INSERT INTO "Products" ("Id", "Author", "CategoryId", "Description", "ISBN", "ListPrice", "Price", "Price100", "Price50", "Title")
VALUES (3, 'Julian Button', NULL, 'Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.

Nunc malesuada viverra ipsum sit amet tincidunt. ', 'RITO5555501', 55.0, 50.0, 35.0, 40.0, 'Vanish in the Sunset');
INSERT INTO "Products" ("Id", "Author", "CategoryId", "Description", "ISBN", "ListPrice", "Price", "Price100", "Price50", "Title")
VALUES (4, 'Abby Muscles', NULL, 'Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.

Nunc malesuada viverra ipsum sit amet tincidunt. ', 'WS3333333301', 70.0, 65.0, 55.0, 60.0, 'Cotton Candy');
INSERT INTO "Products" ("Id", "Author", "CategoryId", "Description", "ISBN", "ListPrice", "Price", "Price100", "Price50", "Title")
VALUES (5, 'Ron Parker', NULL, 'Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.

Nunc malesuada viverra ipsum sit amet tincidunt. ', 'SOTJ1111111101', 30.0, 27.0, 20.0, 25.0, 'Rock in the Ocean');
INSERT INTO "Products" ("Id", "Author", "CategoryId", "Description", "ISBN", "ListPrice", "Price", "Price100", "Price50", "Title")
VALUES (6, 'Laura Phantom', NULL, 'Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.

Nunc malesuada viverra ipsum sit amet tincidunt. ', 'FOT000000001', 25.0, 23.0, 20.0, 22.0, 'Leaves and Wonders');

CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Products"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Products") + 1,
        nextval(pg_get_serial_sequence('"Products"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231125115025_Initial', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products" ADD "ImageUrl" text;

UPDATE "Products" SET "ImageUrl" = NULL
WHERE "Id" = 1;

UPDATE "Products" SET "ImageUrl" = NULL
WHERE "Id" = 2;

UPDATE "Products" SET "ImageUrl" = NULL
WHERE "Id" = 3;

UPDATE "Products" SET "ImageUrl" = NULL
WHERE "Id" = 4;

UPDATE "Products" SET "ImageUrl" = NULL
WHERE "Id" = 5;

UPDATE "Products" SET "ImageUrl" = NULL
WHERE "Id" = 6;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231125115824_AddImageUrlToProduct', '8.0.0');

COMMIT;

